booking_sys/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu, name='menu'),
    path('location/', views.location, name='location'),
    path('bookingsite/', views.BookFormView.as_view(), name='bookingsite'),
    path('bookinglist/', views.BookListView.as_view(), name='bookinglist'),
    path('<pk>/update/', views.BookUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.BookDeleteView.as_view(), name='delete'),
]

eaststreet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('booking_sys.urls')),
]

booking_sys/models.py
from django.db import models
from django.contrib.auth.models import User
from .variables import TIMES, GROUP_SIZE, STATUS


class Booking(models.Model):
    """
    Model for restaurant bookings
    """
    contact = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bookings')
    date = models.DateField()
    time = models.TimeField(choices=TIMES)
    group = models.IntegerField(choices=GROUP_SIZE, default=2)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['date', 'time']

    def __str__(self):
        status_name = dict(STATUS)[self.status]
        return f'{self.date} {self.time} {self.contact} x{self.group} - {status_name}'

booking_sys/forms.py
from django import forms
from .models import Booking
import datetime


class BookingForm(forms.ModelForm):
    """
    Form to allow user-made bookings
    """
    class Meta:
        model = Booking
        fields = ('date', 'time', 'group', 'status')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'status': forms.HiddenInput(),
        }

    def clean_date(self):
        date = self.cleaned_data['date']
        if date <= datetime.date.today():
            raise forms.ValidationError(
                "A booking cannot be made any earlier than tomorrow")
        if date.weekday() == 0:
            raise forms.ValidationError(
                "Sorry, the restaurant is closed on a Monday")
        if date.weekday() == 1:
            raise forms.ValidationError(
                "Sorry, the restaurant is closed on a Tuesday")
        return date

booking_sys/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic, View
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from .models import Booking
from .forms import BookingForm


# Static views for main site

def index(request):
    return render(request, 'index.html')


def menu(request):
    return render(request, 'menu.html')


def location(request):
    return render(request, 'location.html')


# Class views for booking site

class BookFormView(generic.CreateView):
    """
    View to create a new booking
    """
    model = Booking
    form_class = BookingForm
    template_name = 'bookingform.html'
    success_url = '/bookinglist'

    def form_valid(self, form):
        form.instance.contact_id = self.request.user.id
        messages.success(self.request, 'Booking submitted successfully')
        return super(BookFormView, self).form_valid(form)


class BookListView(generic.ListView):
    """
    View to display bookings already made by a user
    """
    model = Booking
    queryset = Booking.objects.order_by('date')
    template_name = 'bookinglist.html'


class BookUpdateView(UserPassesTestMixin, generic.UpdateView):
    """
    View to allow a booking to be updated
    """
    model = Booking
    form_class = BookingForm
    template_name = 'bookingform.html'
    success_url = '/bookinglist'

    def test_func(self):
        return self.request.user.id == self.get_object().contact_id

    def form_valid(self, form):
        form.instance.status = 0
        messages.success(self.request, 'Booking updated successfully')
        return super(BookUpdateView, self).form_valid(form)


class BookDeleteView(UserPassesTestMixin, generic.DeleteView):
    """
    View to allow deletion of a booking
    """
    model = Booking
    template_name = 'bookingdelete.html'
    success_url = '/bookinglist'

    def test_func(self):
        return self.request.user.id == self.get_object().contact_id

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Booking deleted successfully')
        return super(BookDeleteView, self).delete(request, *args, **kwargs)

templates/alerts.html
{% if messages %}

    <div class="container mt-3">
        <div class="row">
            <div class="col-10 col-md-8 col-lg-6 offset-1 offset-md-2 offset-lg-3">

                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="message" role="alert">
                    {{ message | safe}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                
            </div>
        </div>
    </div>

{% endif %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="restaurant, cuisine, food, asian, asia, newtownards">
    <meta name="description" content="Restaurant cuisine inspired by the street-styles of Asia">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="prerender" href="{% static 'images/open.jpg' %}">
    <link rel="prerender" href="{% static 'images/background.jpg' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <title>EastSt. Restaurant</title>
</head>

<body background="{% static 'images/background.jpg' %}">

    <!-- Navbar and Main Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container-fluid">
            <div class="row fixed-bottom">
                <!-- Address and Opening Hours -->
                <div class="col-5 col-md-4 col-lg-4">
                    <h3>Address</h3>
                    <p>23A East St, N'Ards<span class="d-none d-sm-inline">, BT23 7EN</span></p>
                    <h3 class="footer-hours">Opening<span class="d-none d-sm-inline"> Hours</span></h3>
                    <p class="footer-hours">W<span class="d-none d-sm-inline">ed</span>-S<span class="d-none d-sm-inline">un</span> 12.30-10.30pm</p>
                </div>
                <!-- Icons -->
                <div class="col-7 col-md-4 col-lg-4 d-flex justify-content-end justify-content-md-center align-items-center">
                    <div class="footer-icon d-flex justify-content-center align-items-center rounded-circle mx-1">
                        <a href="mailto:eaststrestaurant@gmail.com" target="_blank" aria-label="Contact us via email"><i
                                class="fa-solid fa-envelope"></i></a>
                    </div>
                    <div class="footer-icon d-flex justify-content-center align-items-center rounded-circle mx-1">
                        <a href="https://instagram.com" target="_blank" aria-label="Follow us on Instagram"><i
                                class="fa-brands fa-instagram"></i></a>
                    </div>
                    <div class="footer-icon d-flex justify-content-center align-items-center rounded-circle ms-1 me-3 me-md-1">
                        <a href="https://facebook.com" target="_blank" aria-label="Follow us on Facebook"><i
                                class="fa-brands fa-facebook"></i></a>
                    </div>
                </div>
                <!-- Est. Date -->
                <div class="d-none d-md-flex col-md-4 col-lg-4 d-flex justify-content-end align-items-end">
                    <h2>est. 2023</h2>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
    </script>
    <!-- FontAwesome Icons -->
    <script src="https://kit.fontawesome.com/cdf703ddf8.js" crossorigin="anonymous"></script>
    <!-- JS Alert Auto-Dismiss -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById('message');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>

</body>

</html>

templates/bookingdelete.html
{% extends 'bookingsite.html' %}

{% if user.is_authenticated %}
{% block details %}

    <!-- Deletion confirmation dialog -->
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-9 col-md-7 col-lg-5 col-xl-3 booking-form text-center shadow">
                <h2 class="pt-2">Delete a Booking</h2>
                <p class="mb-0">Are you sure you want to delete this booking?</p>
                <p>NOTE: This action cannot be undone!</p>
                <form method="post">
                    {% csrf_token %}
                    <p class="mb-0">Date: {{ booking.date|date:"D, jS M Y" }}</p>
                    <p class="mb-0">Time: {{ booking.time|time:"H:i" }}</p>
                    <p>Group Size: {{ booking.group }}</p>
                    <button class="btn btn-light mb-3" type="submit">Confirm & Delete</button>
                    <a class="btn btn-light mb-3" href="{% url 'bookinglist' %}">Return</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}
{% endif %}

templates/bookingform.html
{% extends 'bookingsite.html' %}

{% if user.is_authenticated %}
{% block details %}

    <!-- New Booking/Update Form -->
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-sm-7 col-md-6 col-lg-4 col-xxl-3 booking-form text-center shadow">
                <h2 class="pt-2">{% if booking %}Update {% else %}Make {% endif %}a Booking</h2>
                <p class="pb-2">Booking as <em>{{ user.username }}</em>. Please book at least one day in advance. Closed Monday/Tuesday.</p>
                {% if booking %}
                <p class="pt-2">NOTE: updated bookings are reset to 'Pending'</p>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if booking %}
                    <button class="btn btn-light mb-3" type="submit">Confirm & Update</button>
                    <a class="btn btn-light mb-3" href="{% url 'bookinglist' %}">Return</a>
                    {% else %}
                    <button class="btn btn-light mb-3" type="submit">Submit</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div> 

{% endblock %}
{% endif %}

templates/bookinglist.html
{% extends 'bookingsite.html' %}

{% if user.is_authenticated %}
{% block details %}

<div class="container text-light">
    <!-- View heading -->
    <div class="row justify-content-center pt-3">
        <div class="col-12 col-md-10 col-xl-7 bg-table">
            <h2 class="pt-2">Your Bookings</h2>
        </div>
    </div>
    <!-- List headings -->
    <div class="row justify-content-center">
        <div class="col-4 col-md-3 col-xl-2 bg-table">
            <p>Date</p>
        </div>
        <div class="col-2 col-md-1 text-start bg-table">
            <p>Time</p>
        </div>
        <div class="col-2 col-md-1 text-center bg-table">
            <p>Gr<span class="d-none d-sm-inline">ou</span>p</p>
        </div>
        <div class="col-4 col-md-2 col-xl-1 text-end bg-table">
            <p>Status</p>
        </div>
        <div class="d-none d-md-block col-md-3 col-xl-2 text-end bg-table">
            <p>Actions</p>
        </div>
    </div>
    <!-- List of user-made bookings -->
    {% for booking in booking_list %}
        {% if booking.contact_id == user.id %}
        <div class="row justify-content-center">
            <!-- Date (format changes depending on screen size) -->
            <div class="col-4 d-md-none bg-dark pt-1 booking-entry">
                <p>{{ booking.date|date:"d/m/Y" }}</p>
            </div>
            <div class="d-none d-md-block col-md-3 col-xl-2 bg-dark">
                <p>{{ booking.date|date:"D, jS M Y" }}</p>
            </div>
            <!-- Time -->        
            <div class="col-2 col-md-1 text-start bg-dark pt-1 pt-md-0 booking-entry">
                <p>{{ booking.time|time:"H:i" }}</p>
            </div>
            <!-- Group Size -->
            <div class="col-2 col-md-1 text-center bg-dark pt-1 pt-md-0 booking-entry">
                <p>{{ booking.group }}</p>
            </div>
            <!-- Booking Status -->
            <div class="col-4 col-md-2 col-xl-1 text-end bg-dark pt-1 pt-md-0 booking-entry">
                {% if booking.status == 1 %}
                <p>Confirmed</p>
                {% elif booking.status == 2 %}
                <p>Cancelled</p>
                {% else %}
                <p>Pending</p>
                {% endif %}
            </div>
            <!-- Action Buttons -->
            <div class="col-12 col-md-3 col-xl-2 text-end bg-dark pb-3 pb-md-0">
                <!-- 'Update' button does not appear if booking status is 'Cancelled' -->
                {% if booking.status != 2 %}
                <a class="btn btn-light btn-sm" href="{% url 'update' booking.id %}">Update</a>
                {% endif %}
                <a class="btn btn-light btn-sm" href="{% url 'delete' booking.id %}">Delete</a>
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}
{% endif %}

templates/bookingsite.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

    <!-- Navbar for Bookings Site -->
    <nav class="navbar bg-light border-bottom border-body sticky-top navbar-expand-md" data-bs-theme="light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'account_logout' %}">
                <h1><i class="fa-solid fa-stroopwafel"></i> EastSt.</h1>
            </a>
            <button class="navbar-toggler p-1 p-sm-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end text-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link text-dark" href="{% url 'bookingsite' %}">New Booking</a></li>
                    <li class="nav-item"><a class="nav-link text-dark" href="{% url 'bookinglist' %}">Current Bookings</a>
                    </li>
                    <!-- Different 'Logout' links for toggled/untoggled menu -->
                    <li class="nav-item d-md-none rounded bg-dark-subtle"><a class="nav-link text-dark"
                            href="{% url 'account_logout' %}">Logout</a></li>
                    <li class="nav-item d-none d-md-inline"><a class="btn btn-dark"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Active-user details -->
    <div class="container-fluid text-light text-end">
        <p><span class="bg-dark px-2 px-md-3 pb-1"> Logged in as <em>{{ user.username }}</em></span> </p>
    </div>

    <!-- Specific content for page -->
    {% block details %}
    {% endblock %}

    <!-- Allows for displaying of alert messages -->
    {% include 'alerts.html' %}

{% else %}

    {% include '403.html' %}

{% endif %}
{% endblock %}

templates/index.html
{% extends 'mainsite.html' %}
{% load static %}

{% block details %}

<div class="container">
    <div id="index-splash" class="row justify-content-center text-light">        
        <!-- Left panel containg the welcome image -->
        <div id="image-column"
            class="d-none d-md-block col-md-5 col-lg-5 col-xl-4 gx-0 bg-dark border border-end-0 border-dark-subtle border-3">
            <img id="splash-image" class="img-fluid" src="{% static 'images/open.jpg' %}" alt="">
        </div>        
        <!-- Right panel containg opening times and other text -->
        <div id="text-column"
            class="col-9 col-md-7 col-lg-5 col-xl-4 bg-dark text-center border-top border-bottom border-end border-dark-subtle border-3">
            <!-- NB Do not alter borders to 'border border-start-0' as responsive css will not function correctly -->
            <div class="row">
                <div class="top-banner col pt-3 pb-2">
                    <h2 class="d-none d-md-block">Restaurant cuisine inspired by the street-styles of Asia</h2>
                </div>
            </div>
            <div class="row">
                <div class="opening-times col pt-2">
                    <h3 class="pt-3">Opening Times</h3>
                    <p class="pb-3"><em>Last sitting at 9.45pm</em></p>
                    <p>Monday/Tuesday: CLOSED</p>
                    <p>Wednesday: 12.30-10.30pm</p>
                    <p>Thursday: 12.30-10.30pm</p>
                    <p>Friday: 12.30-10.30pm</p>
                    <p>Saturday: 12.30-10.30pm</p>
                    <p>Sunday: 12.30-10.30pm</p>
                </div>
            </div>
            <div class="row">
                <div class="bottom-banner col pt-3">
                    <a class="d-sm d-md-none btn btn-light mx-2 my-1" href="{% url 'menu' %}">Menu</a>
                    <a class="btn btn-light my-1" href="{% url 'account_login' %}">Book Now</a>
                    <p class="pt-2"><i class="fa-solid fa-phone"></i> (028) 9527 1012</p>
                </div>                
            </div>
        </div>
        <!-- Allows for displaying of alert messages -->
        {% include 'alerts.html' %}
    </div>
</div>

{% endblock %}

templates/location.html
{% extends 'mainsite.html' %}
{% block details %}

<div class="container text-light">
    <!-- Google map -->
    <div class="row justify-content-center mt-3 pt-2">
        <div class="col-11 col-xl-9 location-map gx-0 bg-dark">
            <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                src="https://tinyurl.com/eastst-map" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"
                aria-label="Google map showing the location of Belvoir Park Forest">
            </iframe>
        </div>
    </div>
    <!-- Transport info banner -->
    <div class="row justify-content-center">
        <div class="col-11 col-lg-6 col-xl-5 bg-dark pt-1 pt-lg-2 text-center text-lg-start">
            <p><i class="fa-solid fa-car me-2"></i> Parking nearby at Ann St & Kennel Ln</p>
        </div>
        <div class="col-11 col-lg-5 col-xl-4 bg-dark pt-0 pt-lg-2 text-center text-lg-end">
            <p><i class="d-lg-none fa-solid fa-bus-simple me-2"></i> Buses operate from 33 Regent St <i
                    class="d-none d-lg-inline fa-solid fa-bus-simple ms-2"></i></p>
        </div>
    </div>
</div>

{% endblock %}

templates/mainsite.html
{% extends 'base.html' %}
{% block content %}

    <!-- Navbar for Main Site -->
    <nav class="navbar bg-dark border-bottom sticky-top navbar-expand-md" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <h1><i class="fa-solid fa-stroopwafel"></i> EastSt.</h1>
            </a>
            <button class="navbar-toggler p-1 p-sm-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end text-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'menu' %}">Menu</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'location' %}">Location</a></li>
                    <!-- Different 'Bookings' links for toggled/untoggled menu -->
                    <li class="nav-item d-md-none bg-light-subtle rounded"><a class="nav-link" href="{% url 'account_login' %}">Bookings</a></li>
                    <li class="nav-item d-none d-md-inline"><a class="btn btn-light" href="{% url 'account_login' %}">Bookings</a></li>
                </ul>
            </div>
        </div>
    </nav>
     
    <!-- Specific content for page -->
    {% block details %}
    {% endblock %}    

{% endblock %}

templates/menu.html
{% extends 'mainsite.html' %}
{% block details %}

<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <!-- Menu Title -->
        <div class="menu-div col-11 col-md-10 col-lg-8 pt-3 text-center">
            <h2>All-Day Menu</h2>
            <p><em>Wednesday-Sunday 12.30-10.30pm (last orders 9.45pm)</em></p>
        </div>
    </div>
    <div class="row justify-content-center">
        <!-- Left-hand column -->
        <div class="menu-div menu-details-left col-11 col-md-5 col-lg-4 pt-3 text-center">
            <h3>Snacks</h3>
            <p>£6 Spiced egg & chilli jam / £5 Potato chips & bacon / £7 Spring rolls / £7 Lamb lettuce cups</p>
            <h3>Sushi</h3>
            <p>£12 Prawn dynamite roll / £12 Beef maki tempura / £16 Tuna selection / £10 Avocado roll</p>
            <h3>Grill</h3>
            <p>£15 Lamb cutlet / £14 Iberico with shishito pepper / £7 Miso almond corn /
                £7 Teriyaki sweet potato</p>
            <h3>Dumplings</h3>
            <p>£10 Spicy beef and bone marrow / £9 Steamed pork with chilli & peanut /
                £9 Crispy garlic pork dumpling</p>
            <h3>Fish</h3>
            <p>£12 Scallop with ponzu & apple / £11 Tuna tataki with tomato & tarragon / £12 Blackened salmon</p>
        </div>
        <!-- Right-hand column -->
        <div class="menu-div menu-details-right col-11 col-md-5 col-lg-4 pt-md-3 text-center">   
            <h3>Bao</h3>
            <p>£6 Brisket mustard bao / £6 Panko wasabi prawn bao / £6 Kimchi with cucumber & pickle ginger</p>
            <h3>To Share</h3>
            <p>£30 Beef massaman curry with cucumber salad steamed rice /
                £80 Côte de boeuf with miso gravy & choice of 2 sides</p>
            <h3>Sides</h3>
            <p>£7 Duck truffle rice / £6 Spicy wafu iceberg lettuce / £7 Spicy pork & green beans /
                £7 Tempura sésame brocoli / £7 Papaya & thai basil / £6 Wok fried rice</p>
            <h3>Pastry</h3>
            <p>£8 Sticky toffee with banana & miso butterscotch / £7 Brown sugar brûlée /
                £8 Milk chocolate ganache with pineapple</p>
            <h3>Drinks</h3>
            <p><em>Please ask at the restaurant for our daily selection of juices, soft drinks, and alcohol</em></p>
        </div>
    </div>
</div>

{% endblock %}

templates/userbookings.html
{% extends 'bookingsite.html' %}

{% if user.is_authenticated %}
{% block details %}

<div class="container text-light">
    <!-- View heading -->
    <div class="row justify-content-center pt-3">
        <div class="col-12 col-lg-7 bg-table">
            <h2>Your Bookings</h2>
        </div>
    </div>
    <!-- List headings -->
    <div class="row justify-content-center">
        <div class="col-4 col-lg-2 bg-table">
            <p><u>Date</u></p>
        </div>
        <div class="col-2 col-lg-1 text-center bg-table">
            <p><u>Time</u></p>
        </div>
        <div class="col-2 col-lg-1 text-center bg-table">
            <p><u>Group</u></p>
        </div>
        <div class="col-4 col-lg-1 text-end bg-table">
            <p><u>Status</u></p>
        </div>
        <div class="d-none d-lg-block col-lg-2 text-end bg-table">
            <p><u>Actions</u></p>
        </div>
    </div>
    <!-- List of user-made bookings -->
    {% for booking in booking_list %}
    {% if booking.contact_id == user.id %}
    <div class="row justify-content-center">
        <!-- Date (format changes depending on screen size) -->
        <div class="col-4 d-md-none bg-dark">
            <p>{{ booking.date|date:"d/m/Y" }}</p>
        </div>
        <div class="d-none d-md-block col-lg-2 bg-dark">
            <p>{{ booking.date|date:"D, jS M Y" }}</p>
        </div>
        <!-- Time -->        
        <div class="col-2 col-lg-1 text-center bg-dark">
            <p>{{ booking.time|time:"H:i" }}</p>
        </div>
        <!-- Group Size -->
        <div class="col-2 col-lg-1 text-center bg-dark">
            <p>{{ booking.group }}</p>
        </div>
        <!-- Booking Status -->
        <div class="col-4 col-lg-1 text-end bg-dark">
            {% if booking.status == 1 %}
            <p>Confirmed</p>
            {% elif booking.status == 2 %}
            <p>Cancelled</p>
            {% else %}
            <p>Pending</p>
            {% endif %}
        </div>
        <!-- Action Buttons -->
        <div class="col-12 col-lg-2 text-end bg-dark mb-2 mb-sm-0 pb-3 pb-md-0">
            <a class="btn btn-light btn-sm" href="{% url 'update' booking.id %}">Update</a>
            <a class="btn btn-light btn-sm" href="{% url 'delete' booking.id %}">Delete</a>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}
{% endif %}